export const AGREEMENT_ERROR_CODES = {
  AUTH_MISSING: "AGREEMENT_AUTH_MISSING",
  AUTH_INVALID: "AGREEMENT_AUTH_INVALID",
  SESSION_REFRESH_FAILED: "AGREEMENT_SESSION_REFRESH_FAILED",
  STATUS_QUERY_FAILED: "AGREEMENT_STATUS_QUERY_FAILED",
  VERSION_MISMATCH: "AGREEMENT_VERSION_MISMATCH",
  ACCEPT_FAILED: "AGREEMENT_ACCEPT_FAILED",
} as const;
