/**
 * Official URI Gym QR — visual asset encodes plain `GYM`; database `qr_codes.code` is source of truth.
 */

/** Exact string encoded in the official gym QR image. */
export const OFFICIAL_GYM_QR_PAYLOAD = "GYM" as const;

/** Primary public asset (generated by npm run generate:gym-qr). */
export const OFFICIAL_GYM_QR_ASSET_PATH = "/assets/gym_qr.png" as const;

/** Legacy path alias — same file content as gym_qr.png after generate. */
export const LEGACY_GYM_QR_ASSET_PATH = "/assets/qr-gym-uri.png" as const;

/** Database codes that use the official static gym QR in admin/download UI. */
export const GYM_QR_DATABASE_CODES = ["GYM", "URI_GYM_CHECKIN_V1", "cq_perm_gym_v1"] as const;

export function isGymQrDatabaseCode(code: string): boolean {
  const normalized = code.trim().toUpperCase();
  if (normalized === "GYM" || normalized === "URI_GYM_CHECKIN_V1") return true;
  return code.trim().toLowerCase() === "cq_perm_gym_v1";
}

export function gymQrDownloadFilename(): string {
  return "gym_qr.png";
}
